### ISSUE TITLE
Can't perform a expected result for my animation clip.

### ISSUE THREAD

**Issue by slayeryahu** [ykdai/BasicPBC#19]
![B_ U7W}ANKVS4HRY98G)$%4](https://github.com/ykdai/BasicPBC/assets/7860485/a46f4009-d54c-4440-bfac-8df9be6f8034)
[汤圆动画.zip](https://github.com/ykdai/BasicPBC/files/15281452/default.zip)

1.Critical Issue: The output lines have altered the style of my original input lines, resulting in a jagged appearance. This is intolerable.
2.Color Output: The error rate is exceptionally high. (These sketches  are specifically created by my artisitor for the baiscpbc test.)

**Comment by Sarthak-999** [comment]
Hey buddy ,could you please tell the steps to run this program on google colab?
I am really keen to test it ,and would be grateful towards you if you tell me the steps to run it.Thank you in advance.

**Comment by slayeryahu** [comment]
> Hey buddy ,could you please tell the steps to run this program on google colab? I am really keen to test it ,and would be grateful towards you if you tell me the steps to run it.Thank you in advance.

I ran it on my own PC, with graphic card 2080ti 22g.

**Comment by Sarthak-999** [comment]
Can you please tell about the steps to predicate colorized frames?Also if can I do it on google colab?

**Comment by ykdai** [comment]
Hi, I am a little bit busy recently and sorry for replying late. 
1. I have adjusted the threshold algorithm to decrease the line width. I think the current result is now acceptable. Then, you will have 2 solutions:
- If you want to keep the original line, you can pull the code and use `--keep_line`. It will blend the original line to the colorized image.
- Since the colors are discrete, you can edit it and correct the mis-colorized regions using other softwares like Retas PaintMan or Clip Paint Studio. Then, they all have anti-aliasing tool to remove the jagged appearance. If you are using the Adobe After Effect, you can also try this plugin (OLM Smoother): https://olm.co.jp/rd/technology/tools/?lang=en for anti-aliasing.

2. Thank you so much for your feedback. I have tested it and the error rate is indeed very high. We are now training a new version of the model, and will try our best to fix these situations in our next version. I will inform you when it is released. Please stay tuned.

**Comment by slayeryahu** [comment]
> Hi, I am a little bit busy recently and sorry for replying late.
> 
> 1. I have adjusted the threshold algorithm to decrease the line width. I think the current result is now acceptable. Then, you will have 2 solutions:
> 
> * If you want to keep the original line, you can pull the code and use `--keep_line`. It will blend the original line to the colorized image.
> * Since the colors are discrete, you can edit it and correct the mis-colorized regions using other softwares like Retas PaintMan or Clip Paint Studio. Then, they all have anti-aliasing tool to remove the jagged appearance. If you are using the Adobe After Effect, you can also try this plugin (OLM Smoother): https://olm.co.jp/rd/technology/tools/?lang=en for anti-aliasing.
> 
> 2. Thank you so much for your feedback. I have tested it and the error rate is indeed very high. We are now training a new version of the model, and will try our best to fix these situations in our next version. I will inform you when it is released. Please stay tuned.

Thank you, I look forward to your achievement.
