### ISSUE TITLE
How to prepare my own line drawing?

### ISSUE THREAD

**Issue by Johanan528** [ykdai/BasicPBC#29]
Hi, thanks for your excellent work! We also do a line art colorization work, and would like to cite and use your work as a baseline. How should I prepare my own line drawing for actual testing? Is a 3-channel binary (0/255) line OK? This is my line art. 

Thanks again~
![0001 (2)](https://github.com/user-attachments/assets/ffe29e00-ab77-4c63-b8dd-1fead9d3b1a3)
![0000 (2)](https://github.com/user-attachments/assets/3ad54010-e871-4563-aa86-c9814c0dd210)

**Comment by ykdai** [comment]
3-channel binary (0/255) line is okay. You also need to generate the paired segment map and json using the `generate_paired_data` function at `https://github.com/ykdai/BasicPBC/blob/main/paint/colorlabel.py`. Besides, you have to ensure that your ground truth's colors are discrete for real animation.

**Comment by Johanan528** [comment]
Here is my running command, is it correct? Will this automatically generate seg: python inference_line_frames.py --path dataset/test/xx --seg_type trappedball. 
Additionally, can you explain in more detail the sentence 'Besides, you have to ensure that your ground truth's colors are discrete for real animation.' Thank you very much.

**Comment by ykdai** [comment]
Sorry for replying late. Since we will calculate the segment-wise accuracy as our metric, if you need to calculate the metrics, the colors of the ground truth should be segment-wise rather than pixel-wise. However, if you just use our method for inference, you can just run the code `python inference_line_frames.py --path dataset/test/xx --seg_type trappedball`.

**Comment by Johanan528** [comment]
Got it, thanks for your reply!
